name: check-pullrequests

on:
  workflow_dispatch:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install frontmatter github-action-utils
          
      - name: run checks
        run: |
          python utils/check-markdownfiles.py
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: linting.log
